// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5OIpBL2StDNUbZl_0vuIaSseCJm9qh64',
    appId: '1:450487680717:web:28c70ef2ae28c6854c7384',
    messagingSenderId: '450487680717',
    projectId: 'financas-e262b',
    authDomain: 'financas-e262b.firebaseapp.com',
    storageBucket: 'financas-e262b.firebasestorage.app',
    measurementId: 'G-CXX59FNBYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyEPfjCARIkXERkiFL0KK7oaE-mhApNog',
    appId: '1:450487680717:android:a7bd460af2c6194a4c7384',
    messagingSenderId: '450487680717',
    projectId: 'financas-e262b',
    storageBucket: 'financas-e262b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnk-0kuGdNix459M55v1RK7sxrirv8xFg',
    appId: '1:450487680717:ios:ed33f0e733a2a6704c7384',
    messagingSenderId: '450487680717',
    projectId: 'financas-e262b',
    storageBucket: 'financas-e262b.firebasestorage.app',
    iosBundleId: 'com.example.financeiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnk-0kuGdNix459M55v1RK7sxrirv8xFg',
    appId: '1:450487680717:ios:ed33f0e733a2a6704c7384',
    messagingSenderId: '450487680717',
    projectId: 'financas-e262b',
    storageBucket: 'financas-e262b.firebasestorage.app',
    iosBundleId: 'com.example.financeiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5OIpBL2StDNUbZl_0vuIaSseCJm9qh64',
    appId: '1:450487680717:web:999c47e4a61e90414c7384',
    messagingSenderId: '450487680717',
    projectId: 'financas-e262b',
    authDomain: 'financas-e262b.firebaseapp.com',
    storageBucket: 'financas-e262b.firebasestorage.app',
    measurementId: 'G-6QM685JER3',
  );
}
